<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>guide_robot_bt_nodes</name>
  <version>0.0.1</version>
  <description>Custom Nav2 BT action nodes for the guide robot.</description>
  <maintainer email="mook@innopolis.ru">mook</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>behaviortree_cpp_v3</depend>
  <depend>guide_robot_msgs</depend>
  <depend>nav2_behavior_tree</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
